#!/bin/sh
#
# Script for install ZSH

if command -v pkg; then
	echo "I'm in FreeBSD"
	installer='pkg install -y'
elif command -v apt-get; then
	echo "I'm in Debian"
	installer='apt-get install -y'
elif command -v pacman; then
	echo "I'm in ArchLinux"
	installer='pacman -Sy'
else
	echo "Unknown system"
	exit 1
fi

# Install some programms
if ! command -v sudo; then
	${installer} sudo
fi
if ! command -v git; then
	${installer} git
fi
if ! command -v zsh; then
	sudo ${installer} zsh
fi
if ! command -v wget; then
	sudo ${installer} wget
fi
if ! command -v curl; then
	sudo ${installer} curl
fi
if ! command -v python3; then
	sudo ${installer} python
fi
if ! command -v ranger; then
	sudo ${installer} ranger
fi
if ! command -v nano; then
	sudo ${installer} nano
fi
if ! command -v bat; then
	sudo ${installer} bat
fi
if ! command -v duf; then
	sudo ${installer} duf
fi
if ! command -v tldr; then
	sudo ${installer} tldr
fi
if ! command -v btop; then
	sudo ${installer} btop
fi
if ! command -v lsd; then
	sudo ${installer} lsd
fi

# Install font for zsh
# sudo ${installer} fonts-firacode

# Install Oh My Zsh with plugins
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Install my theme heist
# wget -P ~/.oh-my-zsh/themes 'https://raw.githubusercontent.com/sanek200000/Linux_sources/main/heist.zsh-theme'
echo 'PROMPT="╭─%{$fg_bold[yellow]%}%D{%Y-%m-%d %H:%M:%S} %{$fg[white]%}|%{$reset_color%} %{$fg_bold[green]%}%n@%m %{$fg[white]%}|%{$reset_color%} %{$fg_bold[cyan]%}%~%{$reset_color%} %{$fg[white]%}|%{$reset_color%}' > "$HOME/.oh-my-zsh/themes/heist.zsh-theme"
echo '╰─%{$fg_bold[yellow]%}>%{$reset_color%} "' >> "$HOME/.oh-my-zsh/themes/heist.zsh-theme"	
echo 'ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[white]%}[%{$fg[magenta]%}"' >> "$HOME/.oh-my-zsh/themes/heist.zsh-theme"
echo 'ZSH_THEME_GIT_PROMPT_SUFFIX="%{$fg[white]%}]%{$reset_color%}"' >> "$HOME/.oh-my-zsh/themes/heist.zsh-theme"
echo 'ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[white]%} %{$fg[red]%}✗%{$fg[white]%}"' >> "$HOME/.oh-my-zsh/themes/heist.zsh-theme"
echo 'ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[white]%} %{$fg[green]%}✔%{$fg[white]%}"' >> "$HOME/.oh-my-zsh/themes/heist.zsh-theme"

# echo aliaces to ~/.zshrc
if command -v lsd; then
	echo "alias ll='lsd -lAF --group-directories-first'" >> ~/.zshrc
else
	echo "alias ll='ls -lAF --group-directories-first'" >> ~/.zshrc
fi
if command -v duf; then
	echo "alias df='duf'" >> ~/.zshrc
fi
if command -v tldr; then
	echo "alias man='tldr'" >> ~/.zshrc
fi
if command -v btop; then
	echo "alias top='btop'" >> ~/.zshrc
fi
if command -v ranger; then
	echo "alias rr='ranger'" >> ~/.zshrc
	ranger --copy-config=all
fi
echo "alias ee='nano -c'" >> ~/.zshrc
echo "alias h='history 50'" >> ~/.zshrc


# Python code: add heist theme, add plugins
python3 -c "
import os

filename = os.path.expanduser('~/.zshrc')
my_theme='ZSH_THEME=\"heist\"'
new_plugins='plugins=( git zsh-syntax-highlighting zsh-autosuggestions )'

with open(filename, 'r') as f:
    lines = f.readlines()

for i, line in enumerate(lines):
    if line.startswith('ZSH_THEME='):
        lines[i] = f'# {line.strip()}\n{my_theme}\n'
    if line.startswith('plugins=('):
        lines[i] = f'# {line.strip()}\n{new_plugins}\n'

with open(filename, 'w') as f:
    f.writelines(lines)
"

# Install PowerLevel10k
printf '%sDo you want to install powerlevel10k theme? [y/N]%s '
read -r opt
case $opt in
	y*|Y*)
		git clone https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh}/themes/powerlevel10k
		python3 -c "import os

filename = os.path.expanduser('~/.zshrc')
p10k_theme='ZSH_THEME=\"powerlevel10k/powerlevel10k\"'

with open(filename, 'r') as f:
	lines = f.readlines()

for i, line in enumerate(lines):
	if line.startswith('ZSH_THEME='):
		lines[i] = f'# {line.strip()}\n{p10k_theme}\n'

with open(filename, 'w') as f:
	f.writelines(lines)
"
	echo 'you can run `p10k configure` to cinfigure your ZSH';;
	n*|N*|"") echo "Theme change skipped.";;
	*) echo "Invalid choice. Shell change skipped.";;
esac


# make ZSH grate again
chsh -s /usr/bin/zsh

echo 'End script'

zsh
